name: Checker
on:
  pull_request:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm ci
      - name: Run the linter
        run: npm run lint
      - name: Run the formatter
        run: npm run format
        if: failure()
      - name: push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '🚨 Fixed linting issues'
          force-add: 'true'
