name: docker CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'static/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/docker.yml'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/wjtje/website:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
